//! Parser for ALPM `.PKGINFO` files — the `key = value` (spaces around `=`)
//! metadata format embedded at the root of every `.pkg.tar.zst`.
//!
//! This is distinct from the `%KEY%`-delimited `desc` format (see
//! [`crate::format::alpm::desc`]). `.PKGINFO` uses `pkgname = x`, multi-valued
//! keys repeat (`depend = a\ndepend = b`), and `#` starts a comment.

use std::collections::BTreeMap;

/// Ordered map of `.PKGINFO` keys → values (case-sensitive, as pacman is).
#[derive(Debug, Clone, Default)]
pub struct PkgInfo {
    pub fields: BTreeMap<String, Vec<String>>,
}

impl PkgInfo {
    pub fn parse(text: &str) -> Self {
        let mut fields: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let Some((key, value)) = line.split_once('=') else {
                continue;
            };
            fields
                .entry(key.trim().to_string())
                .or_default()
                .push(value.trim().to_string());
        }
        PkgInfo { fields }
    }

    pub fn get(&self, key: &str) -> Option<&str> {
        self.fields.get(key).and_then(|v| v.first()).map(String::as_str)
    }

    pub fn get_vec(&self, key: &str) -> &[String] {
        self.fields.get(key).map(Vec::as_slice).unwrap_or(&[])
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const PKGINFO: &str = "\
# Generated by makepkg
pkgname = acl
pkgbase = acl
pkgver = 2.3.2-2
pkgdesc = Access control list utilities
arch = x86_64
depend = glibc
depend = attr
";

    #[test]
    fn parses_key_value() {
        let p = PkgInfo::parse(PKGINFO);
        assert_eq!(p.get("pkgname"), Some("acl"));
        assert_eq!(p.get("pkgver"), Some("2.3.2-2"));
        assert_eq!(p.get_vec("depend"), &["glibc", "attr"]);
    }

    #[test]
    fn ignores_comments_and_blanks() {
        let p = PkgInfo::parse("# comment\n\npkgname = x\n");
        assert_eq!(p.get("pkgname"), Some("x"));
        assert_eq!(p.fields.len(), 1);
    }
}
